import React from "react";
import { Inter } from "next/font/google";
import PropTypes from "prop-types";

import Footer from "@/components/Footer";
import Header from "@/components/Header";

import "@/public/styles/css/resets.css";
import "@/public/styles/css/globals.css";
import "@/public/styles/scss/utils.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Rebuild Landing Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}

RootLayout.propTypes = {
  children: PropTypes.node,
};
